# --------------------------------------
# Hexo Butterfly Theme Configuration
# Docs: https://butterfly.js.org/
# --------------------------------------

# Navigation Settings
nav:
  logo:
  display_title: true
  display_post_title: true
  fixed: false

menu:
  首页: / || fas fa-home
  归档: /archives/ || fas fa-archive
  分类: /categories/ || fas fa-folder
  标签: /tags/ || fas fa-tags
  照片墙: /photo-wall/ || fas fa-images

# Code Blocks Settings
code_blocks:
  theme: light
  macStyle: false
  copy: true
  language: true
  shrink: false

# Social media links
social:
  fab fa-github: https://github.com/jianglipear || Github || '#24292e'

# Sidebar card author
aside:
  card_author:
    button:
      link: https://github.com/jianglipear

# Share System (custom: 小红书 / 小黑盒)
share:
  use: custom
  custom:
    xiaohongshu_link: https://xhslink.cn/o/212RVYinsUE
    xiaoheihe_link: https://web.xiaoheihe.cn/tools/invite_friend/share?heybox_id=72312265
    xiaohongshu_icon: /img/xiaohongshu.png
    xiaoheihe_icon: /img/xiaoheihe.png

# Custom CSS / JS inject
inject:
  head:
    - <link rel="stylesheet" href="/css/custom.css">

# Image Settings
favicon:
avatar:
  img: /img/avatar.jpg
  effect: false

# Post Settings
post_meta:
  page:
    date_type: created
    categories: true
    tags: true
  post:
    date_type: both
    categories: true
    tags: true

# Footer Settings
footer:
  owner:
    enable: true
    since: 2026
  copyright: true
  custom_text:
